server:
  port: 8887
spring:
  datasource:
    # 数据库
    url: jdbc:mysql://43.138.16.193:3306/qiyu_community?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    name: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接池（不确定要不要设置）
    druid:
      username: root
      password: 123456
  # 自动部署
  devtools:
    restart:
      exclude: static
  # Themeleaf
  thymeleaf:
    # 禁用缓存
    cache: false
# pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

# MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# qiniuyun
qiniu:
  accessKey: qC5AE63lVkFoEYqpyzCt9WyFV8H8kLh57ZntHZZa # 公钥
  secretKey: wqIIQ81JNjplCwJAV1dtgZumqNsEzGX0XD6nUxFB # 私钥
  bucketName: sevenfish  #存储空间名称
  path: http://photo.4668251.top